lib/protoparser/opentelemetry: fix typo in code
#
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/pb
lib/protoparser/opentelemetry/pb/pb.go:1683:19: undefined: lctx

Bug introduced in
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/55b530b95a4bd991cb217ad963aa21976a450100